# Test para ver la generalidad del algoritmo

En este notebook se van a desarrollar distintos tests para comprobar la generalidad del algoritmo, es decir, se va a comprovar que el tamaño de las muestras y las divisiones no tengan que ser muy específicas.

## Definición del algoritmo y de su inversa

Vamos a definir una función, que a su vez, va a llamar a la función implementada en C y ya compilada para poder usar.

In [3]:
from transform_data import ffi, lib

def t_data(src, dest, sub_shape, inverse=False):

    typesize = src.dtype.itemsize

    src2 = ffi.from_buffer(src)
    dest2 = ffi.from_buffer(dest)

    shape = src.shape

    dimension = len(src.shape)

    lib.transform_data(src2, dest2, typesize, sub_shape, shape, dimension, inverse)

## Testeando el algoritmo

### Inicialización de los parámatros

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import tables as tb

### 1. Test

En este test la el tamaño de las dimensiones de los datos no va a ser potencia de 2, pero el tamaño de las subdivisiones de las dimensiones va a ser divisor de todas las dimensiones.

In [5]:
# Definición de los datos

a, b = 12, 15

src = np.arange(a * b, dtype=np.int32).reshape(a, b)

dest = np.empty(src.size, dtype = src.dtype).reshape(src.shape)
src2 = np.empty(src.size, dtype = src.dtype).reshape(src.shape)

sub_shape = (3, 3)

# Test de las dos funciones creadas

t_data(src, dest, sub_shape, inverse=False)
t_data(dest, src2, sub_shape, inverse=True)

np.testing.assert_array_equal(src, src2)

try:
    np.testing.assert_array_equal(src, src2)
    print("OK. La transformación funciona correctamente.")
except Exception:
    print("ERROR. Las matrices no coinciden.")
    
print()

# Impresión de los datos reales y los datos modificados

print("Datos originales")
print(src)

print()

print("Datos modificados")
print(dest)

OK. La transformación funciona correctamente.

Datos originales
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159 160 161 162 163 164]
 [165 166 167 168 169 170 171 172 173 174 175 176 177 178 179]]

Datos modificados
[[  0   1   2  15  16  17  30  31  32   3   4   5  18  19  20]
 [ 33  34  35   6   7   8  21  22  23  36  37  38   9  10  11]
 [ 24  25  26  39  40  41  12  13 

### 2. Test

En este test la el tamaño de las dimensiones de los datos no va a ser múltiplo de 2. Además, el tamaño de las subdivisiones de las dimensiones va a ser divisor, sólo, de su dimensión.

In [6]:
# Definición de los datos

a, b = 9, 8

src = np.arange(a * b, dtype=np.int32).reshape(a, b)

dest = np.empty(src.size, dtype = src.dtype).reshape(src.shape)
src2 = np.empty(src.size, dtype = src.dtype).reshape(src.shape)

sub_shape = (3, 2)

# Test de las dos funciones creadas

t_data(src, dest, sub_shape, inverse=False)
t_data(dest, src2, sub_shape, inverse=True)

np.testing.assert_array_equal(src, src2)

try:
    np.testing.assert_array_equal(src, src2)
    print("OK. La transformación funciona correctamente.")
except Exception:
    print("ERROR. Las matrices no coinciden.")
    
print()

# Impresión de los datos reales y los datos modificados

print("Datos originales")
print(src)

print()

print("Datos modificados")
print(dest)

OK. La transformación funciona correctamente.

Datos originales
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71]]

Datos modificados
[[ 0  1  8  9 16 17  2  3]
 [10 11 18 19  4  5 12 13]
 [20 21  6  7 14 15 22 23]
 [24 25 32 33 40 41 26 27]
 [34 35 42 43 28 29 36 37]
 [44 45 30 31 38 39 46 47]
 [48 49 56 57 64 65 50 51]
 [58 59 66 67 52 53 60 61]
 [68 69 54 55 62 63 70 71]]


### 3. Test

En este test la el tamaño de las dimensiones de los datos no va a ser múltiplo de 2. Además, el tamaño de las subdivisiones de las dimensiones no va a ser divisor de su dimensión.

In [7]:
# Definición de los datos

a, b = 14, 11

src = np.arange(a * b, dtype=np.int32).reshape(a, b)

dest = np.empty(src.size, dtype = src.dtype).reshape(src.shape)
src2 = np.empty(src.size, dtype = src.dtype).reshape(src.shape)

sub_shape = (5, 3)

# Test de las dos funciones creadas

t_data(src, dest, sub_shape, inverse=False)
t_data(dest, src2, sub_shape, inverse=True)

try:
    np.testing.assert_array_equal(src, src2)
    print("OK. La transformación funciona correctamente.")
except Exception:
    print("ERROR. La transformación no funciona correctamente.")
    
print()
    
# Impresión de los datos reales y los datos modificados

print("Datos originales")
print(src)

print()

print("Datos modificados")
print(dest)

ERROR. La transformación no funciona correctamente.

Datos originales
[[  0   1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43]
 [ 44  45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142]
 [143 144 145 146 147 148 149 150 151 152 153]]

Datos modificados
[[  0   1   2  11  12  13  22  23  24  33  34]
 [ 35  44  45  46   3   4   5  14  15  16  25]
 [ 26  27  36  37  38  47  48  49   6   7   8]
 [ 17  18  19  28  29  30  39  40  41  50  51]
 [ 52   0   1   2  11  12  13  22  23  24  33]
 [ 89  90  99 100

## Conclusiones

Se puede ver que el tamaño de las dimensiones no tiene por qué ser múltiplo de 2. Para que funcione el algoritmo solo hace falta que el tamaño de cada subdivisón sea divisor del tamaño de la dimensión asociada.

## Test para 'redimensionar' los datos a dimensiones de potencias de 2

In [15]:
a, b = 10, 10

src = np.arange(a * b, dtype=np.int32).reshape(a, b)

dest = np.empty(src.size, dtype = src.dtype).reshape(src.shape)
src2 = np.empty(src.size, dtype = src.dtype).reshape(src.shape)

sub_shape = (2, 2)

typesize = src.dtype.itemsize

src2 = ffi.from_buffer(src)
dest2 = ffi.from_buffer(dest)

shape = (8, 8)

dimension = len(src.shape)

inverse = False

lib.transform_data(src2, dest2, typesize, sub_shape, shape, dimension, inverse)

In [16]:
print(dest)

[[ 0  1  8  9  2  3 10 11  4  5]
 [12 13  6  7 14 15 16 17 24 25]
 [18 19 26 27 20 21 28 29 22 23]
 [30 31 32 33 40 41 34 35 42 43]
 [36 37 44 45 38 39 46 47 48 49]
 [56 57 50 51 58 59 52 53 60 61]
 [54 55 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
